### ISSUE TITLE
Robot Localization

### ISSUE THREAD

**Issue by eionpaulos** [Team612/612-2023-Charged-Up#16]
Goal:
- Create a system for determining the location of the robot, with x and y position, and the orientation θ of the robot, in order to find the exact position of the robot on the field at any time. This system should work in any field, meaning it needs to use the data from the robot sensors and camera and not prior knowledge of the field.

Tasks:
- Find data from 3 sensors (IMU + encoder, and AprilTags)
- Kalman filter

Links:
- https://digital.wpi.edu/pdfviewer/n296x089m
- https://docs.wpilib.org/en/stable/docs/software/advanced-controls/state-space/index.html
- https://file.tavsys.net/control/controls-engineering-in-frc.pdf
- https://www.kalmanfilter.net/background.html
- https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

- https://docs.photonvision.org/en/latest/docs/examples/simaimandrange.html

**Comment by ericstone1** [comment]
https://digital.wpi.edu/pdfviewer/n296x089m

**Comment by ctrl-alt-delete101** [comment]
#5 has been solved. We don't need to include IMU data our sensor readings are already superb.
