### ISSUE TITLE
Vision(April Tags)

### ISSUE THREAD

**Issue by Abhinav-Vadlamani** [Team612/612-2023-Charged-Up#5]
Requirements:

- Press button to align robot with April Tag
- Determine camera placements
- Fully test trajectories with vision (finish tuning, measure)
- Start up with beagle bone
- Updating drivetrain odometry with vision position
- Triangulating with 2 April Tags

**Comment by ctrl-alt-delete101** [comment]
Has been solved by #15 and #33
