### ISSUE TITLE
Driver Assistance

### ISSUE THREAD

**Issue by Abhinav-Vadlamani** [Team612/612-2023-Charged-Up#9]
Requirement:

- Button to automatically score from where you are
- Robort Localization(Creating a field to show drivers where the robot is in the field)
- Autobalance in teleop
- Decision trees and state machines
- Sensor fusion for pose estimation

**Comment by ctrl-alt-delete101** [comment]
Basically done I'm going to say that we haven't had time to think about Decisions Trees but everything else has been completed and tested. 
#33
